# Generated by Django 3.2 on 2021-05-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_answer_classify_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collect_ques',
            field=models.ManyToManyField(to='accounts.Question'),
        ),
    ]
