# Generated by Django 4.0.5 on 2022-06-27 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=64, verbose_name='博客分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('images', models.ImageField(blank=True, max_length=256, upload_to='%Y%m/file/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='文章创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='文章修改时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('blog_types', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.blogtypes')),
            ],
        ),
    ]
