# Generated by Django 4.0.5 on 2022-06-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_blogtypes_blogtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='博客分类名称')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_type',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.AddField(
            model_name='blog',
            name='category_id',
            field=models.PositiveSmallIntegerField(default=False, verbose_name='文章分类 ID，关联到分类表的 ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.PositiveIntegerField(verbose_name='管理员 ID，关联到管理员表的 ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='BlogType',
        ),
    ]
