# Generated by Django 4.0.5 on 2022-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcategory_remove_blog_blog_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_tag',
            field=models.CharField(default="It's Max_blog", max_length=255, verbose_name='把文章标题显示在 URL 里'),
        ),
    ]
