# Generated by Django 4.0.5 on 2022-07-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title_tag',
            field=models.CharField(default="It's Max_blog", max_length=255, verbose_name='在后台编辑博客的时候可以定义博客的标签'),
        ),
    ]
